name: 自动关闭Issue

on:
  issues:
    types:
      - labeled

permissions:
  issues: write


jobs:
  close_issue:
    runs-on: ubuntu-latest

    steps:
      - name: 自动处理Issue
        uses: actions/github-script@v7
        with:
          script: |

            const label = context.payload.label.name;

            let comment = null;


            if (label === "已完成") {

              comment = `
  ## ✅ Issue 已完成

感谢你的反馈！

该问题已经完成处理，我们会在后续版本中发布相关修复或更新。

感谢你对项目的支持！
`;

            }


            if (label === "不予处理") {

              comment = `
## ❌ Issue 不予处理

感谢你的反馈。

经过评估，该内容暂时不符合当前项目规划，因此不会进行处理。

感谢理解！
`;

            }


            if (label === "无法修复") {

              comment = `
## ❌ Issue 无法修复

感谢你的反馈。

由于技术限制、依赖限制或实现成本等原因，该问题目前无法修复。

如果未来条件允许，我们会重新评估。

感谢支持！
`;

            }


            if (!comment) {
              return;
            }


            // 添加评论
            await github.rest.issues.createComment({

              owner: context.repo.owner,

              repo: context.repo.repo,

              issue_number: context.issue.number,

              body: comment

            });



            // 关闭 Issue

            await github.rest.issues.update({

              owner: context.repo.owner,

              repo: context.repo.repo,

              issue_number: context.issue.number,

              state: "closed"

            });
